# Site settings
title: Jad Aboul Hosn
description: "Welcome to my data science portfolio!\n\n Full-stack data scientist (cowboy data scientist works too!)\n\n I do everything from data wrangling to building automated pipelines through training & deploying models. I am constantly on the hunt for the next challenging engineering problem. I strive to test & push new technologies and packages that enable data scientists to go back to doing 'data scienc-y' stuff without getting lost in the tech overhead. 
My top strengths include strong organizational skills, designing, and engineering machine learning solutions, and building ML models! 
I recently graduated from ASU with an MS in Computer Engineering. I completed courses in Artificial Intelligence, Statistical Machine Learning, Distributed Database Systems, and Data Visualization. \n\nCompetencies: data science, machine learning, cloud computing, Python/R/SQL, statistical analysis"
url: 'http://jadhosn.github.io'
baseurl: ''

google_analytics: 'UA-124636227-2'
# disqus_shortname: 'your-disqus-name'

# resume: https://drive.google.com/file/d/1hSzpeAh3X7fY5HHe-qVCZ4bHxkIdFKoU
resume: https://jadhosn.github.io/resume.pdf

author:
  name: 'Jad Aboul Hosn'
  email: jadhosn@asu.edu
  #twitter_username: joshgerdes
  #facebook_username: joshgerdes
  github_username:  jadhosn
  linkedin_username:  jadahosn
  medium_username:  jhosn13
  kaggle_username: jhosn13

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']

theme: jekyll-theme-hacker