# Site settings
title: Jad Aboul Hosn
description: "Welcome to my data science portfolio!\n\n
I am a junior data scientist, passionate about leveraging data to drive business insgihts and decisions.\n
My expertise include designing and building predictive models using various statistical machine learning techniques. I build data pipelines complete with feature extraction and transformations that fead into production models. \n
I have 1+ years of experience doing quantitative analysis, handling millions of rows of data, and developing insights from a large array of datasets, and applying cutting edge methods in machine learning, optimization and statistics."
url: 'http://jadhosn.github.io'
baseurl: ''

google_analytics: 'UA-124636227-2'
# disqus_shortname: 'your-disqus-name'

resume: https://drive.google.com/open?id=1hSzpeAh3X7fY5HHe-qVCZ4bHxkIdFKoU

author:
  name: 'Jad Aboul Hosn'
  email: jadhosn@asu.edu
  #twitter_username: joshgerdes
  #facebook_username: joshgerdes
  github_username:  jadhosn
  linkedin_username:  jadahosn
  medium_username:  jhosn13
  kaggle_username: jhosn13

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
